services:
  # 1. Backend Web Service (Node.js & Express API)
  - type: web
    name: job-portal-backend-api
    runtime: node
    plan: free
    region: oregon
    rootDir: full-stack-job-portal-server-main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_NAME
        value: job_portal_token
      - key: COOKIE_SECRET
        value: job_portal_cookie_secret_2026
      - key: JWT_SECRET
        value: job_portal_secret_key_jwt_2026_super_secure
      - key: DB_STRING
        value: mongodb+srv://solairajansaro_db_user:solairajansaro_123@cluster0.s0ewk45.mongodb.net/job-portal?retryWrites=true&w=majority

  # 2. Frontend Static Site (React + Vite Client)
  - type: static
    name: job-portal-frontend-client
    rootDir: full-stack-job-portal-client-main
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false

